version: '3'
services:
#Service dev toma el Dockerfile de ./dev
 dev:
  build: ./dev
  hostname: dev
  env_file: 
  - "dev/envfile"
  #Mapeos del container al anfitrión
  ports:
  - "8080:80"
  - "8043:443"
  - "8006:3306"
  #Mapeo del directorio de repos
  volumes:
  - ~/repos:/root/repos
  - mysql:/var/lib/mysql
  - apache:/var/www/html

volumes:
 mysql:
 apache:
